apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Values.certificate.name}} 
spec:
  secretName: {{.Values.certificate.secretName}}
  dnsNames:
    {{- range .Values.certificate.dnsNames }}
      - {{ .  }}
    {{- end }}
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
