apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{.Values.middlewares.name}} 
spec:
  basicAuth:
    secret: {{.Values.middlewares.secret}} 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.middlewares.secret}}
data:
  users: {{.Values.secret.users}} 
